- name: install and start nginx
  hosts: frontend
  tasks:
  - name: install nginx
    ansible.builtin.service:
      name: nginx
      state: present

  - name: start nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes