- name: install and start nginx
  hosts: frontend
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.service:
      name: nginx
      state: present

  - name: restart nginx
    ansible.builtin.service:
      name: nginx
      state: restarted
      
  - name: enable nginx
    ansible.builtin.service:
      name: nginx
      enabled: yes